### ISSUE TITLE
Minimum *.razor page must have `@model` *and* `OnGetAsync`

### ISSUE THREAD

**Issue by Eilon** [rynowak/RazorPages#1]
From my test, it seems that the minimum `.razor` page is essentially this:

```
@model Customer

@functions {
    public async Task OnGetAsync()
    {
    }
}

Hi!
```

Note that it must have an `@model`, and also must specify a Get action, e.g. `OnGetAsync`. Then it'll just render the expected text, `Hi!`.

**Comment by rynowak** [comment]
58003355e342d2029971ef6690115482bfefb983 fixes the issue requiring `OnGetAsync`

**Comment by rynowak** [comment]
The issue about `@model` comes from here - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/RazorPageActivator.cs

The page is being activated twice, and the built in `IRazorPageActivator` doesn't know how to to deal with the `Page` class.

**Comment by rynowak** [comment]
a9dd9b4a9775c6a3fe3175e0ce517e9f526588c5 fixes the issue requiring `@model`

**Comment by Eilon** [comment]
Cool, will try it out this afternoon.
