### ISSUE TITLE
Need to add TempData property to Page class

### ISSUE THREAD

**Issue by DamianEdwards** [rynowak/RazorPages#4]
Have to get it off of `PageContext` right now.

**Comment by rynowak** [comment]
This is here already - https://github.com/rynowak/RazorPages/blob/master/src/Microsoft.AspNetCore.Mvc.RazorPages/Page.cs#L151

What exactly did you see?

**Comment by DamianEdwards** [comment]
I get a null ref. If you replace the property with `public ITempDataDictionary TempData => PageContext.TempData;` it works.

**Comment by rynowak** [comment]
Fixed. This ended up being somewhat more complicated. We had a 'dummy' `ViewContext` being created instead of flowing the `PageContext`. This would likely break more than just `TempData`. Fixed now.
